name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3
      - name: Install Dependencies
        run: npm install

      # Step 4
      - name: Run Unit Tests
        run: npm run test:unit